### ISSUE TITLE
Bot: assess whether id, stats, effect are necessary

### ISSUE THREAD

**Issue by AlphaKretin** [DawnbrandBots/bastion-bot#14]
This is a discussion rather than an immediate code issue.

My initial thoughts are that I'm happy to cut `stats` and `effect`, they saw little use and embeds mean they don't save a ton of space which was the initial use-case. `id` is a bit more useful for a lightweight conversion between `password` and `name`, but there might be a more appropriate avenue for that now especially with the `kid` complicating matters.

**Comment by kevinlul** [comment]
Let's keep some form of id then. Does the Slash Commamd schema allow for choosing exactly one of two arguments? This way we could let the user choose between KIDs and passwords. We could also split the command, but that would require three commands to cover all two-way combinations. We could also have one command with an additional argument to specify the type, and we convert appropriately? Lastly, we could also do `#` implying KID?

**Comment by AlphaKretin** [comment]
My vision for an `/id` command (perhaps with a different name) is entering password or KID and receiving both + name. So there are no two-way combinations, you always get the same output. But I don't think I like splitting it into even as few as 2 commands. I think the simplest solution, if the Schema doesn't support "exactly one required", is to simply make both optional and respond with an instructive error if neither are input. If both are selected, we could may be return them if they match but behaviour is unclear if they don't. Error? Show details for both? Pick one to take priority? I see the appeal of finding a solution that doesn't allow this outcome, but I feel the simplicity of this solution in other areas (one command with directly labelled input fields) remains preferable. I could maybe have my mind changed though, in particular with regards to the option of a single input field with the user somehow indicating if it's a KID. However, the way we have the user denotes this will have to be carefully considered. We don't want to sacrifice making the input field a number type, I feel.

**Comment by kevinlul** [comment]
.id currently takes either password or name and returns both. So if we always want to return the same output, then admittedly an extra argument indicating whether the input is a KID or password doesn't make sense when it's a name. However, I think this option is the best as it is better extensible for localization — this parameter specifies whether the input is a KID, password, or in some language, and then we could possibly try to infer if left off (the `#` KID prefix, searching all languages at once)

**Comment by AlphaKretin** [comment]
Alright, that makes sense. I'll close this issue and explicitly add implementing `/id` to the board.
