### ISSUE TITLE
Price information

### ISSUE THREAD

**Issue by kevinlul** [DawnbrandBots/bastion-bot#140]
Need to find new data sources for card prices, including our own caching if necessary to improve latency. Known options:

- https://yugiohprices.com/ (old Bastion)
- YGOPRODECK API
- [TCGPlayer](https://help.tcgplayer.com/hc/en-us/articles/201577976-How-can-I-get-access-to-your-card-pricing-data-)
- CardMarket
- CoolStuffInc
- eBay
- Amazon
- Troll and Toad
- Poke Order
- Card Central
- Ideal 808
- Alter Reality Games
- CoreTCG

use code AlphaKretin5 to ????

**Comment by AlphaKretin** [comment]
Of note here: 
yugiohprices.com currently has severe latency issues
The YGOPRODECK API aggregates the 5 below it, but only lists a minimum price.
CardMarket is an EU store with prices in EUR, and may be worth looking it in addition to whichever USD source.
Alter Reality Games is a quite old store, and I don't know if it still runs, I mostly hear about it in historical contexts (e.g. the tournament series they ran). Briefly browsing their site, their offerings seem to be quite outdated.

**Comment by kevinlul** [comment]
Related old issue: AlphaKretin/bastion-bot#58

**Comment by kevinlul** [comment]
Not related to implementation, but an application could be price summaries in `/deck`

**Comment by kevinlul** [comment]
Implementation to port: https://github.com/AlphaKretin/ygoprodeck-tag-bot/blob/master/modules/price.ts
