### ISSUE TITLE
Implement <>

### ISSUE THREAD

**Issue by kevinlul** [DawnbrandBots/bastion-bot#152]
This will partially succeed the classic [embed view](https://github.com/AlphaKretin/bastion-bot/wiki/Commands-for-users#card-search). Functions like a basic `/search`, but multiple may be triggered at once from a message (old limit: 3).

- [x] Check what servers have [`fullBrackets`](https://github.com/AlphaKretin/bastion-bot/wiki/Commands-for-server-mods#configuration) configured, and then determine the priority for administrative `/bracket left` and `/bracket right` commands.
- [x] Choose a delimiter for specifying `inputLanguage` and `resultLanguage`. Old Bastion used trailing `,en,ja`, for example.

Should only trigger for search strings not containing `(`. The left parenthesis does not appear in card names. These will still be routed to the old bot for various unofficial cards, to allow for partial rollout of the new bot on official cards. This heuristic does catch a lot, but not some cards in [this category](https://yugipedia.com/wiki/Category:Cards_with_no_OCG/TCG_counterpart), like C/C/C or Cookpal, which originally would not need to have `(anime)` included for the search to resolve.

**Comment by larry126** [comment]
Typing `(anime)` and etc. while may be okay on a computer, it becomes rather tedious on a mobile device as most mobile keyboards require you to switch back and forth to use symbols such as parenthesis and full brackets (and often parenthesis and full brackets are on separate keyboards so more switchings).
User-wise utilising the terms `anime/manga/vg/etc.` as trigger words would be the most intuitive and doesn't require to you leave the main keyboard. However, the term `manga` does have a conflict with the card `Manga Ryu-Ran` and there may come other implications with other terms.
Perhaps we could only enable the word `anime` as an extra trigger word, as it is the most frequently searched category and the old bot does catch some cards from other unofficial categories when you search with this word (so it covers even more cards).
In extra, currently Bastion users often do not use parenthesis or specify categories for unofficial-exclusive cards, so whatever the change ends up to be, it should be informed to and likely require the users to adapt regardless for the time being.

**Comment by kevinlul** [comment]
Several servers with significant usage have custom _fullBrackets_ configured, meaning we cannot just disable and revert those servers to `<>`. One possible solution to this in the transitional period when both instances are listening to `<>`:
- freeze _fullBrackets_ configuration (existing settings preserved, changes disallowed)
- hardcode that configuration in the new instance so both instances are triggered by the same brackets for the few servers that have an override
- note to these servers that they must ask us to change their settings

**Comment by kevinlul** [comment]
Since the old _fullBrackets_ feature was infrequently used (and generally only set to `[]`), any successor feature should simply provide a limited list of choices for delimiters, as arbitrary ones have unpredictable results.

**Comment by AlphaKretin** [comment]
> Since the old _fullBrackets_ feature was infrequently used (and generally only set to `[]`), any successor feature should simply provide a limited list of choices for delimiters, as arbitrary ones have unpredictable results.

One use-case for customised brackets was to make the feature more obscure, to avoid conflicts with other bots. We should either provide such an option in the list of custom brackets, or add an option (likely through a separate command) to disable this kind of search entirely (with users still able to use ` /search` instead).

**Comment by kevinlul** [comment]
What's the use case for making the bracket search more obscure but NOT punting Bastion out of the channel? Chat commands? If that's the case, this may be moot with command use permissions being governed separately from channel access.

**Comment by kevinlul** [comment]
I haven't come up with more solutions than freezing _fullBrackets_ configuration, which seems to me the simplest approach minimally impacting existing users. What do you think?

**Comment by AlphaKretin** [comment]
> What's the use case for making the bracket search more obscure but NOT punting Bastion out of the channel? Chat commands? If that's the case, this may be moot with command use permissions being governed separately from channel access.

You raise a good point. This wasn't true previously bc other commands were through messages but now that it's all Slash this should be a good option to recommend. 

> I haven't come up with more solutions than freezing _fullBrackets_ configuration, which seems to me the simplest approach minimally impacting existing users. What do you think?

Yeah, I like the transition plans outlined here.

**Comment by kevinlul** [comment]
For preprocessing messages:
- https://discord.com/blog/how-discord-renders-rich-messages-on-the-android-app
- https://github.com/brussell98/discord-markdown (or some variation based on KhanAcademy's simple-markdown)

**Comment by kevinlul** [comment]
Tasks remaining:
- [ ] tests for matching input and result language (implies more modularization)
- [ ] delete listener
- [ ] actually supporting alternate bracket options for the servers using them
- [ ] shared config to enable this search server-by-server for slower rollout?

**Comment by kevinlul** [comment]
Full dial-up achieved with some exceptions #196
