### ISSUE TITLE
/deck: attempting to remove upload button after the reply was deleted logs error

### ISSUE THREAD

**Issue by kevinlul** [DawnbrandBots/bastion-bot#185]
No operation impact, just unnecessary log noise.

Internal log:
- https://discord.com/channels/381294999729340417/896778500013449266/1025690612676165683

**Comment by AlphaKretin** [comment]
The "correct" way to do this would be to check if the reply still exists before trying to edit it, but that seems like unnecessary overhead, fetching it every time. Could simply check for an error we know is a non-issue before logging it and choose not to.

**Comment by kevinlul** [comment]
This is moot with 21ba47f665699bfa31d4e1c0f73f92435f44fe08 (#534)
