### ISSUE TITLE
New Rush Artworks

### ISSUE THREAD

**Issue by buh2** [DawnbrandBots/bastion-bot#281]
Artworks from the new Rush Duel game on the switch have just been datamined and added to the wiki, but the rush-duel-art command doesn't seem to be able to fetch them yet.

**Comment by kevinlul** [comment]
VG: https://yugipedia.com/wiki/Yu-Gi-Oh!_RUSH_DUEL:_Saikyo_Battle_Royale!!_Let%27s_Go!_Go_Rush!!
Art category: https://yugipedia.com/wiki/Category:Yu-Gi-Oh!_RUSH_DUEL:_Saikyo_Battle_Royale!!_Let%27s_Go!_Go_Rush!!_card_artworks

**Comment by buh2** [comment]
Uhm, I don't quite understand.

I'm asking if the command will be updated to be able to get these artworks aswell. Sorry for any misunderstanding.

**Comment by kevinlul** [comment]
I was taking notes for myself. Do you know if this game includes every card from the previous game? If that is the case, I believe the only change required is to update the URL here

https://github.com/DawnbrandBots/bastion-bot/blob/master/src/commands/rush-duel.ts#L45

**Comment by buh2** [comment]
Aaaah, understood.

And yes, it has every card from the previous game.

**Comment by kevinlul** [comment]
Are you the same person as @Buh4 from #228? 😅

**Comment by buh2** [comment]
Oh, yeah XD

I seem to have multiple Github accounts, I'm kindof a forgetful person...

Either way, thank you for your work as always.

**Comment by kevinlul** [comment]
As with last time, you can test it out on the preview bot in the support server.
