### ISSUE TITLE
Represent Link Arrows using custom emoji

### ISSUE THREAD

**Issue by kevinlul** [DawnbrandBots/bastion-bot#311]
Discord stopped formatting the Unicode arrows as emoji:
![image](https://user-images.githubusercontent.com/6320810/235571331-f250f1a3-9d82-4cf0-8218-645076870d7d.png)

Furthermore, for monsters with high Link Rating, this format becomes hard to comprehend, though it is still theoretically readable by screen readers. Formatting as text is still hard to comprehend, e.g. **Link Arrows**: Up-Left, Left, Down, Right, Up-Right, Up

A custom emoji would be easier to comprehend for most people not using screen readers: ![image](https://cdn.discordapp.com/emojis/1102764589533368412.webp?size=44&quality=lossless)![image](https://cdn.discordapp.com/emojis/1102764593941581864.webp?size=44&quality=lossless)![image](https://cdn.discordapp.com/emojis/1102764586295373864.webp?size=44&quality=lossless)![image](https://cdn.discordapp.com/emojis/1102764591529865356.webp?size=44&quality=lossless)

However, this requires 40 emojis and hardcoding 40 mappings for each combination of Link Arrows that have been printed, because each emoji is identified by a snowflake when it is uploaded (existing examples: https://github.com/DawnbrandBots/bastion-bot/blob/master/src/card.ts#L65-L123). @Ice-Pendragon has already created these graphics.

Consider implementing a per-server option to use custom Link Arrows emoji over printing the arrows, with fallback to printing the arrows when the emoji is not available.

**Comment by Ice-Pendragon** [comment]
Per-server options will be brillant. I suggest these options:

Arrow emojis (default and intended to) : Such as ⬅️⬆️➡️⬇️
Arrow symbols (current but not intended to) : Such as ←↑→↓
Plain texts : Such as "Left, Up, Right, Down"
Keypad numbers: Such as 8462 (which way Konami uses on their filenames for official database) 
Custom emojis : Such as above screenshot. I'm working on it

**Comment by Ice-Pendragon** [comment]
[LinkMarker.zip](https://github.com/DawnbrandBots/bastion-bot/files/11378207/LinkMarker.zip)
A SQLite3 database file and Excel file (compressed to .zip) about mappings

**Comment by kevinlul** [comment]
Almost one year later... it looks better on mobile that it does on desktop/web. Desktop/web samples:

![image](https://github.com/DawnbrandBots/bastion-bot/assets/6320810/183a2c74-c912-4daf-a5c0-24d3337a675a)
![image](https://github.com/DawnbrandBots/bastion-bot/assets/6320810/5fc90051-8dd1-419d-987c-096c1999cb3a)
![image](https://github.com/DawnbrandBots/bastion-bot/assets/6320810/5be44acb-1434-4593-bad5-d60ec097db8e)
![image](https://github.com/DawnbrandBots/bastion-bot/assets/6320810/05d6f313-2a26-4931-b1f7-3f4170317a3d)
![image](https://github.com/DawnbrandBots/bastion-bot/assets/6320810/4fc4cde5-ccec-40b6-b31a-8e2ccc015995)
![image](https://github.com/DawnbrandBots/bastion-bot/assets/6320810/0d139efa-0574-4cf7-bef3-ac913c5e2a5f)
![image](https://github.com/DawnbrandBots/bastion-bot/assets/6320810/8da82f37-e928-410d-bc41-83509c1c14d1)

**Comment by Ice-Pendragon** [comment]
Extremely cool!

**Comment by kevinlul** [comment]
We probably will need to make adjustments. The screenshots look larger than default zoom in-client on my computer.

**Comment by kevinlul** [comment]
You can try it out on the preview bot.
