### ISSUE TITLE
Bastion is slacking off???

### ISSUE THREAD

**Issue by Capt-Blitz** [DawnbrandBots/bastion-bot#454]
Hey...I don't know exectly what is happening but on the GoldenNovaYugioh discord server we have noticed a trend of Bastion just refusing to acknowledge serch queries. 
We don't know whats happening, can one of you look at it?

**Comment by kevinlul** [comment]
Do you have a server ID?

![image](https://github.com/DawnbrandBots/bastion-bot/assets/6320810/ac54fa1e-3514-4dde-af85-f0e2e07bfa4a)

**Comment by kevinlul** [comment]
Observed similar behaviour in a different server on April 23 and April 25. However, as far as I can tell, in those cases, the earlier attempts are not being sent from Discord to Bastion. I don't have evidence to rule out some bug in Discord.js event processing or the initial Bastion preprocessing.

https://github.com/DawnbrandBots/bastion-bot/blob/3169c02a440654b1d378707d0f66a90818f41bb8/src/events/message-search.ts#L245-L269

**Comment by Capt-Blitz** [comment]
I don't see a server ID option, but here is the invite link
https://discord.gg/UPD9dcxu

**Comment by kevinlul** [comment]
Per https://discord.com/api/v8/invites/UPD9dcxu?with_counts=true, the server ID is 745060455327858819. Checking recent logs.

**Comment by kevinlul** [comment]
From the past week, the only thing I've spotted is two searches within a second for "share the pain" today by different users.

**Comment by kevinlul** [comment]
Approved to log channel 751160897032028361 in the same way as below

https://github.com/DawnbrandBots/bastion-bot/blob/1024cbb384abed4d6f947a75c7d8e8ed3b9be1f4/src/events/message-search.ts#L246-L253

**Comment by kevinlul** [comment]
Logging is active now. Please let us know if you spot any misses effective from May 10 at 3:47 am ET.

**Comment by kevinlul** [comment]
Four months ago in #434, a change was introduced that synchronized the ignore condition between the message ping and message search listeners. This added a new condition to ignore replies for message search. This behaviour is incorrect, unintuitive, and undocumented as all replies are ignored, not just direct replies to Bastion, and there are no merits of ignoring even those for message search. This should account for the majority of cases of this "heisenbug", though there still remain uncommon cases of Discord not sending the message to Bastion.

**Comment by kevinlul** [comment]
@Capt-Blitz A fix was deployed. Please let me know if this restores your search experience or if you have any other feedback.

**Comment by kevinlul** [comment]
The team reached out on Discord to the opener and confirmed the fix. There is still a follow-up idea to add a context menu command to resend to Bastion, but the reply fix covers most situations.
