### ISSUE TITLE
Choosing a localization system

### ISSUE THREAD

**Issue by kevinlul** [DawnbrandBots/bastion-bot#46]
gettext: https://www.npmjs.com/package/node-gettext, https://github.com/smhg/gettext-parser, something to generate POTs
https://github.com/messageformat/Jed  (another gettext)
messageformat: https://github.com/messageformat/messageformat custom system, doesn't seem too relevant
Airbnb Polyglot: https://www.npmjs.com/package/node-polyglot
https://www.npmjs.com/package/globalize
https://www.npmjs.com/package/i18n, seems to target express
https://www.npmjs.com/package/i18next, most popular, but is key-based
https://www.npmjs.com/package/y18n, dependency of yargs and only targets CLI so concurrent commands may clobber each other

**Comment by kevinlul** [comment]
I prefer a gettext-like system where you have the original natural language strings so you still have the context in code, as long as we can generate the translation files and they're easy enough to use. We don't need browser support or framework support, but we need some what of keeping locale per command so concurrent invocations don't clobber each other in a shared instance.

**Comment by AlphaKretin** [comment]
At a glance, I do like the gettext style, which seems to be similar to the sort of thing I'd hand-roll, i.e. its interface is intuitive to me. Polyglot seems to be a similar take on the same idea, just with a slightly different feature set. Globalize (ironic to use an -ise/-ize suffix word in this context...) seems to be more concerned with i18n of non-word concepts like date strings and number formats, I don't see translation examples in its docs. This may be useful functionality though, to complement a lib that handles translation but not other i18n. The series of libs named for i18n requiring a server to be spun up, rather than reading from files like gettext, seems ill suited to our purposes.

**Comment by kevinlul** [comment]
I would like to sit on this to think about and come back later to make sure we're making the right decision. My main concern with gettext systems are that the packages are not as popular and may not be as well supported, though gettext is a very old and established system. It can deal with plurals, but apparently doesn't support grammatical gender, and I'm not sure how the date and number formatting play into it, which will be relevant for set dates and prices.

**Comment by AlphaKretin** [comment]
Yes, there's no reason to rush into a decision here and now. If we do find a system that meets our needs except for date and number formatting, we can supplement that with Globalize, even if that doesn't fit our other needs. I don't know if things like grammatical gender or Japanese's politeness levels are things up to the translation system, that would just be a matter of what constitutes a good loc in our database of translations. The only hiccup I can currently forsee in this context is pronouns for the user, if there is not one single appropriate option - but we would not have a way to determine what is appropriate for each user anyway so it's kind of a moot point.

**Comment by kevinlul** [comment]
Another one: https://ttag.js.org/

**Comment by kevinlul** [comment]
Actual gettext-like options to try out:
- node-gettext + gettext-parser, extract with xgettext
- ttag suite
- i18n on a `{}` per-command context object
- i18next with the key as the fallback

**Comment by kevinlul** [comment]
- xgettext is bad at parsing TypeScript. In-JavaScript solutions would just add more complexity
- ttag-cli po2json just uses gettext-parser
