### ISSUE TITLE
Configuring localization: /locale

### ISSUE THREAD

**Issue by kevinlul** [DawnbrandBots/bastion-bot#47]
Discord has added [locale fields to interactions](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-structure). This is supported in [Discord.js as of 13.6](https://github.com/discordjs/discord.js/releases/tag/13.6.0). How we might use this information in Bastion:

Text output (labels and card text) from Bastion can fall back to the per-user `locale` in direct messages or the per-server `guildLocale` in servers as a default, instead of always requiring a locale parameter. We do not use the user-specific locale in servers as the results may be public and thus leak the user's default language setting, assuming it isn't already leaked from other sources. The latter is only available for configuration in community servers and affects the whole server, so additionally:

Add a `/locale` command to show the current configuration for the channel. It can support arguments to configure overrides. In direct messages, this overrides the user's Discord locale setting. In servers, this can configure the language for the whole server (overriding the community server setting if present), or for this channel (overriding any server-wide settings).

**Comment by kevinlul** [comment]
Discord has added [locale fields to interactions](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-structure). This is supported in [Discord.js as of 13.6](https://github.com/discordjs/discord.js/releases/tag/13.6.0). How we might use this information in Bastion:

Text output (labels and card text) from Bastion can fall back to the per-user `locale` in direct messages or the per-server `guildLocale` in servers as a default, instead of always requiring a locale parameter. We do not use the user-specific locale in servers as the results may be public and thus leak the user's default language setting, assuming it isn't already leaked from other sources. The latter is only available for configuration in community servers and affects the whole server, so additionally:

Add a `/locale` command to show the current configuration for the channel. It can support arguments to configure overrides. In direct messages, this overrides the user's Discord locale setting. In servers, this can configure the language for the whole server (overriding the community server setting if present), or for this channel (overriding any server-wide settings).

**Comment by AlphaKretin** [comment]
This all sounds good. Hopefully foreign-language servers have accurate locales and don't regularly default to en-US or anything. Using guild locale over user locale seems like the better option even independent of privacy concerns, as a multilingual user may be posting in a server where the expected language spoken matches up with the guild locale and not their own.

**Comment by kevinlul** [comment]
We need our override system for sure, as the "preferred server language" setting that ends up becoming the guild locale field is only a thing for community servers. The supported languages are the same as the languages that Discord supports, i.e. has translations for: https://discord.com/developers/docs/dispatch/field-values#predefined-field-values-accepted-locales

**Comment by AlphaKretin** [comment]
> We need our override system for sure, as the "preferred server language" setting that ends up becoming the guild locale field is only a thing for community servers.

criiiiipes. I hope that's just a rollout or something because that's an awful attitude, that i18n is only a thing special big servers need and not, like, an a11y feature.

**Comment by kevinlul** [comment]
The thing is, I think "Server Primary Language" is only used as an attribute in the server discovery system. There's no other indication of specifically this property in the Discord client to a user. The other reason we would need it is for per-channel overrides, since locale isn't specified by channel at all.

At least this is a superset of the languages for Yu-Gi-Oh releases or that we plan to target 😅 
Discord has made the mistake of using national flags to represent languages though 👎

**Comment by AlphaKretin** [comment]
Well, perhaps we should make a formal proposal on their feedback tracker that since guild locale can be a useful property for bots to act upon, it should be rolled out to all servers and guild owner should be made more aware of it as a setting. ~~As long as they don't decide that it would be a privacy violation like reading messages is and make it all harder for us...~~

**Comment by kevinlul** [comment]
![image](https://user-images.githubusercontent.com/6320810/149686449-f0f5495c-8306-4b84-90a7-8d57d20ff185.png)

It basically doesn't have purpose beyond some messages for server owners and discovery. What language people use in a server isn't actually determined by hidden labels 😛 

We'll definitely always have the locale for the calling user though.

**Comment by kevinlul** [comment]
https://github.com/discord/discord-api-docs/issues/2313#issuecomment-761126291

Last year: "Returning you the locale of the user is currently deemed a privacy issue, as stated earlier"

**Comment by AlphaKretin** [comment]
That thread is frustrating. "We can't expose the server locale for you to use because it has no use". We're proposing a use! Just tell server admins in the settings menu that it's for bots and commands.
> It basically doesn't have purpose beyond some messages for server owners and discovery. What language people use in a server isn't actually determined by hidden labels 😛
Well yeah, the point is the server admin would set the label in reflection of server activity.

**Comment by kevinlul** [comment]
I forgot, threads are a new type of channel. How should they intersect with this feature?

**Comment by AlphaKretin** [comment]
Hmm good question. Their impermanence might make configuring a locale for them awkward, perhaps they should inherit from the parent channel? But maybe it wouldn't actually be an issue.

**Comment by kevinlul** [comment]
This is considered complete when all appropriate commands (/search, /deck, /id) make use of this system, notwithstanding localisation of UI labels (#46).

**Comment by kevinlul** [comment]
System is functional. Onboarding more commands or more locales will be an ongoing effort.
